---
- name: Install FPM Dependencies
  hosts: localhost
  tasks:
      - package: 
            name: "{{item}}"
            state: latest
        with_items:
        - ruby-devel
        - gcc
        - make
        - rpm-build

- name: Install FPM Gem
  hosts: localhost
  tasks:
      - gem:
            name: fpm
            user_install: no
            state: latest
